<?php

namespace App\Tests\Controller;

use PHPUnit\Framework\TestCase;
use App\Controller\StockController;
use App\Repository\StockRepository;
use App\Entity\Stock;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\QueryException;
use Doctrine\ORM\OptimisticLockException;
use Doctrine\ORM\ORMException;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\MockObject\MockBuilder;
use PHPUnit\Framework\MockObject\Call;
use PHPUnit\Framework\MockObject\InvokedArgs;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias2;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias2;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias3;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias3;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias4;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias4;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias5;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias5;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias6;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias6;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias7;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias7;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias8;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias8;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias9;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias9;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias10;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias10;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias11;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias11;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias12;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias12;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias13;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias13;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias14;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias14;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias15;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias15;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias16;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias16;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias17;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias17;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias18;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias18;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias19;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias19;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias20;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias20;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias21;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias21;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias22;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias22;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias23;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias23;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias24;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias24;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias25;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias25;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias26;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias26;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias27;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias27;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias28;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias28;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias29;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias29;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias30;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias30;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias31;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias31;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias32;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias32;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias33;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias33;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias34;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias34;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias35;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias35;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias36;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias36;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias37;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias37;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias38;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias38;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias39;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias39;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias40;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias40;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias41;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias41;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias42;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias42;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias43;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias43;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias44;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias44;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias45;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias45;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias46;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias46;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias47;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias47;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias48;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias48;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias49;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias49;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias50;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias50;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias51;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias51;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias52;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias52;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias53;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias53;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias54;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias54;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias55;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias55;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias56;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias56;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias57;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias57;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias58;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias58;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias59;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias59;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias60;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias60;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias61;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias61;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias62;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias62;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias63;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias63;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias64;
use PHPUnit\Framework\MockObject\MockBuilder as MockBuilderAlias64;
use PHPUnit\Framework\MockObject\MockObject as MockObjectAlias65;
use PHPUnit\Framework\